const NO_SUBSCRIPTION = 'NO_SUBSCRIPTION';
const FILE_NOT_FOUND = 'FILE_NOT_FOUND';
const RESOURCE_SUBSCRIPTION = 'RESOURCE_NOT_FOUND';
const UNHANDLED_ERROR = 'UNHANDLED_ERROR';
const NOT_FOUND = 'NOT_FOUND';

module.exports = {
  NO_SUBSCRIPTION,
  FILE_NOT_FOUND,
  RESOURCE_SUBSCRIPTION,
  UNHANDLED_ERROR,
  NOT_FOUND,
};
